[package]
name = "bevy_crt"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy", tag = "v0.17.0-rc.2", version = "0.17.0-rc.2" }

[profile.dev.package."*"]
opt-level=3